CREATE  TABLE  IF NOT EXISTS user (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Username VARCHAR(20) NOT NULL,
    Password VARCHAR (200) NOT NULL,
	Email VARCHAR (35) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Name VARCHAR (25) NOT NULL,
Description Text NOT NULL,
Price FLOAT NOT NULL,
On_Action boolean  default false,
CategoryId INT NOT NULL,
Image_path VARCHAR(1024) default 'No_Picture.jpg',
CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (CategoryId) REFERENCES category(Id)
);

CREATE TABLE IF NOT EXISTS category (
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NAME VARCHAR (25) NOT NULL
);

INSERT INTO user (Username, Password, Email) VALUES ("Test1" , "123456", "testuser@test.com");